# Generated by Django 2.1.1 on 2018-09-28 18:06

from django.db import migrations, models
import restaurants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20180927_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='category',
            field=models.CharField(max_length=120, null=True, validators=[restaurants.validators.validate_category]),
        ),
    ]
